### ISSUE TITLE
hi I got an error (E0433) when compiling

### ISSUE THREAD

**Issue by iqzoj69m** [themockingjet/ore-cli-gpu#1]
error[E0433]: failed to resolve: use of undeclared crate or module `equix`
  --> src/mine.rs:99:38
   |
99 |                     let mut memory = equix::SolverMemory::new();
   |                                      ^^^^^ use of undeclared crate or module `equix`

warning: unused import: `std::sync::Mutex`
  --> src/mine.rs:31:5
   |
31 | use std::sync::Mutex;
   |     ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `rayon::prelude`
  --> src/mine.rs:32:5
   |
32 | use rayon::prelude::*;
   |     ^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0433`.
warning: `ore-cli` (bin "ore") generated 2 warnings
error: could not compile `ore-cli` (bin "ore") due to previous error; 2 warnings emitted

**Comment by espoir1989** [comment]
Don't even try. It's not as good as the cpu

**Comment by pokitpeng** [comment]
How to use it？
